### PR TITLE
Fix compatibility with Android API < 24

### LINKED ISSUE #3: Android Issues
Hi,

I recently switched Natrium to use JNano classes and functions, for code simplification and because I planned on using JNano anyway for Mnemonics down the line.

I ran into a couple issues, the first one may not be an issue with library but an issue with my build settings (I haven't been able to figure it out yet though)

On a android 6.0, 32-bit device (armeabi-v7a) - I get the following when trying `NanoKeys.createPrivateKey`

```11-29 10:35:47.750 6190-6190/co.banano.natriumwallet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.banano.natriumwallet, PID: 6190
    java.lang.NoClassDefFoundError: com.rotilho.jnano.commons.-$$Lambda$NanoKeys$To3fvqZ6OqDSbslOGNAscJLDYzE
        at com.rotilho.jnano.commons.NanoKeys.createPrivateKey(NanoKeys.java:12)
        at co.banano.natriumwallet.KaliumUtil.seedToPrivate(KaliumUtil.java:48)
        at co.banano.natriumwallet.model.Credentials.setSeed(Credentials.java:55)
        at co.banano.natriumwallet.ui.intro.IntroWelcomeFragment$ClickHandlers.lambda$onClickNewWallet$0(IntroWelcomeFragment.java:74)
        at co.banano.natriumwallet.ui.intro.-$$Lambda$IntroWelcomeFragment$ClickHandlers$J_jelFXY-c9L5iUyzoeIh90MgC4.execute(lambda)
        at io.realm.Realm.executeTransaction(Realm.java:1431)
        at co.banano.natriumwallet.ui.intro.IntroWelcomeFragment$ClickHandlers.onClickNewWallet(IntroWelcomeFragment.java:72)
        at co.banano.natriumwallet.databinding.FragmentIntroWelcomeBindingImpl$OnClickListenerImpl1.onClick(FragmentIntroWelcomeBindingImpl.java:147)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Separate, but also occurring on older android versions is an issue with `NanoSeeds.generateSeed()`

I get the exception:

```
java.lang.NoSuchMethodError: No static method getInstanceStrong()Ljava/security/SecureRandom; in class Ljava/security/SecureRandom; or its super classes (declaration of 'java.security.SecureRandom' appears in /system/framework/core-libart.jar)
        at com.rotilho.jnano.commons.NanoSeeds.generateSeed(NanoSeeds.java:25)
        at co.banano.natriumwallet.KaliumUtil.generateSeed(KaliumUtil.java:29)
        at co.banano.natriumwallet.ui.intro.IntroWelcomeFragment$ClickHandlers.lambda$onClickNewWallet$0(IntroWelcomeFragment.java:74)
        at co.banano.natriumwallet.ui.intro.-$$Lambda$IntroWelcomeFragment$ClickHandlers$J_jelFXY-c9L5iUyzoeIh90MgC4.execute(lambda)
        at io.realm.Realm.executeTransaction(Realm.java:1431)
        at co.banano.natriumwallet.ui.intro.IntroWelcomeFragment$ClickHandlers.onClickNewWallet(IntroWelcomeFragment.java:72)
        at co.banano.natriumwallet.databinding.FragmentIntroWelcomeBindingImpl$OnClickListenerImpl1.onClick(FragmentIntroWelcomeBindingImpl.java:147)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

This is something I could account for myself if you do not want to, but appears older Android SDKs do not support `SecureRandom.getInstanceStrong()` , which is likely why NWC went with a custom implementation as seen here: https://github.com/bbedward/natrium-nano-wallet/blob/master/app/src/main/java/co/banano/natriumwallet/util/LinuxSecureRandom.java

I'd appreciate any help on these problems, of course Natrium full source can be seen at https://github.com/bbedward/natrium-nano-wallet

On 64-bit, newer devices everything that I have used has worked with no problems.

Thanks!

### PR DESCRIPTION
**Pull request by bbedward**
The rationale of these changes is mainly android-focused,  some java 8+ features (Streams, some lambdas, etc.) only work in Android API v24+

We still have ~30% of Android devices running on pre-v24 android versions, so in that regard it makes sense as Android developers probably want to include that audience when developing their apps.

So this PR just rewrites some parts of various classes to not use java 8+ features (no Streams, lambdas, functional interfaces, etc.)

Does not address:
1) NanoWorks
2) Seed generation `getInstanceStrong()` is not supported until API level 26 on android

fixes #3

### CODE REVIEW

File: src/main/java/com/rotilho/jnano/commons/Hashes.java [hunk 1]
```diff
@@ -17,11 +13,15 @@ private Hashes() {
     }
 
     public static byte[] digest(int digestSize, byte[]... byteArrays) {
-        requireNonNull(byteArrays, "Byte Arrays can't be null");
+    	if (byteArrays == null) {
+    		throw new NullPointerException("Byte Arrays can't be null");
+    	}
```
Comment (bbedward) [inline src/main/java/com/rotilho/jnano/commons/Hashes.java:18]: This is the equivalent of `requireNonNull` essentially, but could disregard this since the null pointer exception would occur eventually regardless if `byteArrays` is null

`requireNonNull` is only available in android API 19 and above, which is why this was changed

**Comment by bbedward** [comment]
Tested these changes and natrium is working well now on  5.0+ android devices (haven't gotten to thoroughly test anything < API 19 yet).

**Comment by rotilho** [comment]
LGFM
